[alias]
rel = "build --release"
inst = "install --path ."
clip = "clippy --release"
pub = "publish"
up = "update --verbose"

[build]
target = "x86_64-unknown-linux-gnu"

[install]
target = "x86_64-unknown-linux-gnu"

[publish]
target = "x86_64-unknown-linux-gnu"

[clippy]
target = "x86_64-unknown-linux-gnu"

[update]
target = "x86_64-unknown-linux-gnu"
